### ISSUE TITLE
The default config breaks HiddenOre

### ISSUE THREAD

**Issue by MudkipGuy** [DevotedMC/HiddenOre#27]
On a clean install, the following error happens when launching the server:

```
[14:08:33 WARN]: [HiddenOre] An error occured while loading config!
java.lang.NullPointerException
        at com.github.devotedmc.hiddenore.Config.grabLimits(Config.java:214) ~[HiddenOre-1.2.5.jar:?]
        at com.github.devotedmc.hiddenore.Config.doLoad(Config.java:164) ~[HiddenOre-1.2.5.jar:?]
        at com.github.devotedmc.hiddenore.Config.loadConfig(Config.java:51) [HiddenOre-1.2.5.jar:?]
        at com.github.devotedmc.hiddenore.HiddenOre.onEnable(HiddenOre.java:30) [HiddenOre-1.2.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
```

This appears to be caused by lines 190 through 197 of the default config file:

```yml
    # Chance for XP to drop when this gen/drop occurs
    # you can add this section to "biomes" as well for unique biome-level drops
    # chance and amount are modified by tool.
    xp:
     # standard amount config; amount for "always" value, minAmount/maxAmount for randomized size
     amount: 1
     # Chance of XP to generate; this is a separate chance and computed separately for XP
     chance: 1.0
```

And removing these lines causes HiddenOre to work as intended

Tested on Windows 10

**Comment by ProgrammerDan** [comment]
I haven't observed this despite testing. Perhaps was a shortlived problem?
